### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by suthat** [tradle/react-native-passport-reader#2]
The compile error has occurred with React Native 0.59.

**Comment by suthat** [comment]
For more information

Task :react-native-passport-reader:compileDebugJavaWithJavac FAILED

node_modules/react-native-passport-reader/android/src/main/java/io/tradle/nfc/RNPassportReaderPackage.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

**Comment by mvayngrib** [comment]
@suthat looks like it was fixed a while ago but not published. Try version 1.0.2 (just published)

**Comment by suthat** [comment]
@mvayngrib Thanks.
