### ISSUE TITLE
Request for Android build (update)

### ISSUE THREAD

**Issue by suthat** [tradle/react-native-passport-reader#3]
As we 've known that Gladle force `compile` (in dependencies {  }) to the old fashion, but the rise of using `implementation` instead.  Please help to change this sort of update as well as editing the `buildToolsVersion` for current RN and Android building technologies. 

Thank you and appreciated your contribution.

**Comment by mvayngrib** [comment]
ur right, please send a PR

**Comment by suthat** [comment]
OK.
