### ISSUE TITLE
The library takes very long long time to read NFC

### ISSUE THREAD

**Issue by suthat** [tradle/react-native-passport-reader#4]
I installed and implemented your libraries as well as able to generally run the very basic application. It just reads the data from my passport following your sample code. However, for more than 20 times of testing (with and without photo object), the average time that it spent to reading is about 4 to 5 minutes which is unacceptable. My issues are:

1. Is there any kind of reading statuses or real-time log return from PassportReader for more details?
2. Is there other examples of the PassportReader API to improve and enhance the reading time?

Ps. RN 0.59.5
Dev on Mac OS Mojave
Device is Samsung Galaxy S9

Please help.

**Comment by mvayngrib** [comment]
4-5 minutes? That doesn't sound right. You mean you place the phone on the passport page and wait 4 minutes until it returns some data? Have you tried with/without the debugger?

**Comment by suthat** [comment]
Yes, I used to try for both with/without the debugger, still, 4 minutes and some seem forever. It seems like something went wrong, but I have no sense how to debug and find it.

**Comment by mvayngrib** [comment]
@suthat unfortunately i won't have time to investigate this. This library was adapted from https://github.com/tananaev/passport-reader , you can try to ask @tananaev for guidance

**Comment by suthat** [comment]
@mvayngrib Okay. I got it and thanks a lot for your time.
